apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: document-service-autoscaler
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: document-service-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 280Mi
#290 Mebibytes is aboout 304MB

#when average memory used across all pods of document service increased more than 280Mi, the auto scaling will trigger.

