apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpascaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization       
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target: 
        type: AverageValue
        averageValue: 10Mi

#averageUtilization(integer)	averageUtilization is the target value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods. Currently only valid for Resource metric source type

#averageValue(Quantity)	averageValue is the target value of the average of the metric across all relevant pods (as a quantity)

#type(string)	type represents whether the metric type is Utilization, Value, or AverageValue

#value(Quantity)	value is the target value of the metric (as a quantity).
#
#Controller Manager compare the metrics received from Metrics server API in regular intervals and scales the deployment once the defined threshold is crossed. HPA is a control loop as defined by the parameter --horizontal-pod-autoscaler-sync-period. By default it's set to 15 seconds
